const fs = require('fs');
const icon192 = "iVBORw0KGgoAAAANSUhEUgAAAMAAAADAAQMAAABF76zFAAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAACNJREFUeNrtwTEBAAAAwiD7p14b2gAAAAAAAAAAAAAAAAAAuA4wAAABKj9YAAAAAElFTkSuQmCC";
const icon512 = "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIAAQMAAADOtka5AAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAAEVJREFUeNrtwQENAAAAwqD3T+3sARQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAODUAUAAAAE7I3O7AAAAAElFTkSuQmCC";
fs.writeFileSync('icon-192.png', Buffer.from(icon192, 'base64'));
fs.writeFileSync('icon-512.png', Buffer.from(icon512, 'base64'));
console.log('Icons fixed');
